language: python

python: 3.5
sudo: required
dist: trusty

env:
    global:
        - CXX=g++-4.8
        - secure: ajoP9pA/FYH+1sFwGKHlQ8PoGqRIjdmqEnwo44AA5j6c1NMsgiToA420lPm8Lp0cko5YK3ppBlGlvbRWu5JXVxl0vMtZTLf3FM2w99viddrRCkh4sMef2DzkXXYOW4Tnew/8pmaOtTn3UtNG/feJHkBzHLEDUuN0TA07Y6UaWHc=
        # do not load /etc/boto.cfg with Python 3 incompatible plugin
        # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
        - BOTO_CONFIG=/doesnotexist
    #matrix:
    #    - TARGET=client
    #    - TARGET=server
    #    - TARGET=e2e_first_chrome
    #    - TARGET=e2e_second_chrome
    #    - TARGET=e2e_third_chrome

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - elasticsearch-1.7
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - mongodb-org-server
    - elasticsearch
    - xvfb
    - build-essential
    - libudev-dev
    - clang-3.3
    - fakeroot
    - git
    - libgnome-keyring-dev
    - g++-4.8
    - google-chrome-stable

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - nvm install node
    - nvm use node
    - node --version
    - npm config set loglevel warn
    - npm install -g npm@latest grunt-cli
    - cp $TRAVIS_BUILD_DIR/client/config.sample.js $TRAVIS_BUILD_DIR/client/config.js
    - npm install -g grunt-cli ;
    - pip install requests
    - export DISPLAY=:99.0
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
    - export CHROME_BIN=`which google-chrome`
    - $CHROME_BIN --version

install:
    - cd $TRAVIS_BUILD_DIR/server
    - pip install -r requirements.txt
    - cd $TRAVIS_BUILD_DIR/client && npm install && cd .. ;

before_script:
    - ./scripts/elastic.sh
    - sudo service elasticsearch restart && sleep 10
    - cd $TRAVIS_BUILD_DIR/server
    - (nohup env SUPERDESK_URL='http://127.0.0.1:5000/api' SUPERDESK_CLIENT_URL='http://127.0.0.1:9000' WEB_CONCURRENCY=3 WEB_TIMEOUT=8 SUPERDESK_TESTING='True' honcho start &)
    - cd $TRAVIS_BUILD_DIR/client
    - SYNDICATION=true grunt build --server='http://127.0.0.1:5000/api' --ws='ws://127.0.0.1:5100'
    - cd dist
    - while [ ! -f index.html ]; do sleep .5; done
    - (nohup python3 -m http.server 9000 &)
    - cd $TRAVIS_BUILD_DIR/server
    - (nohup env SUPERDESK_URL='http://127.0.0.1:5000/api' SUPERDESK_CLIENT_URL='http://127.0.0.1:9000' WEB_CONCURRENCY=3 WEB_TIMEOUT=8 SUPERDESK_TESTING='True' honcho start &)

script:
    - cd $TRAVIS_BUILD_DIR/server && nosetests --all-modules ;
    - cd $TRAVIS_BUILD_DIR/server && behave --format progress2 --logging-level ERROR ;
    - cd $TRAVIS_BUILD_DIR/server && flake8 ;
    - cd $TRAVIS_BUILD_DIR/client && npm test ;
    - cd $TRAVIS_BUILD_DIR/server
    - python3 manage.py app:initialize_data;
    - python3 manage.py users:create -u admin -p admin -e 'admin@example.com' --admin ;
    - python3 manage.py register_local_themes ;
    - python3 manage.py schema:migrate ;
    - cd $TRAVIS_BUILD_DIR/client
    - ./node_modules/.bin/webdriver-manager update
    - ./node_modules/.bin/protractor protractor-conf.js

after_script:
    - killall -9 python
