language: python

python: 3.4

sudo: false

env:
    global:
        - secure: ajoP9pA/FYH+1sFwGKHlQ8PoGqRIjdmqEnwo44AA5j6c1NMsgiToA420lPm8Lp0cko5YK3ppBlGlvbRWu5JXVxl0vMtZTLf3FM2w99viddrRCkh4sMef2DzkXXYOW4Tnew/8pmaOtTn3UtNG/feJHkBzHLEDUuN0TA07Y6UaWHc=
    matrix:
        - TARGET=client
        - TARGET=e2e_chrome
        - TARGET=server

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - elasticsearch-1.7
    packages:
    - mongodb-org-server
    - elasticsearch

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - $HOME/.cache/bower

before_install:
    - if [ "${TARGET}" = "client" ] || [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        npm config set loglevel warn ;
        npm install -g grunt-cli bower ;
      fi
    - if [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24 &&
        wget -N --no-verbose 'https://storage.googleapis.com/chromium-browser-continuous/Linux_x64/353893/chrome-linux.zip' && unzip chrome-linux.zip &&
        export CHROME_BIN=`pwd`/chrome-linux/chrome && $CHROME_BIN --version ;
      fi

install:
    - if [ "${TARGET}" = "server" ] || [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        cd server &&
        pip install -r requirements.txt &&
        cd .. ;
      fi
    - if [ "${TARGET}" = "client" ] || [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        cd client && npm install --python=python2.7 && bower install &&
        cd .. ;
      fi

before_script:
    - if [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        cd client ;
        ./node_modules/.bin/webdriver-manager update &&
        grunt build ;
        cd dist ;

        while [ ! -f index.html ]; do sleep .5; done ;
        (nohup python3 -m http.server 9000 &) ;
        cd ../.. ;
      fi

script:
    - if [ "${TARGET}" = "server" ]; then
        cd server && nosetests --all-modules && cd .. ;
      fi
    - if [ "${TARGET}" = "server" ]; then
        cd server &&
        behave --format progress2 --logging-level ERROR &&
        cd .. ;
      fi
    - if [ "${TARGET}" = "server" ]; then
        cd server && flake8 && cd .. ;
      fi
    - if [ "${TARGET}" = "client" ]; then
        cd client && npm test && cd .. ;
      fi
    - if [ "${TARGET}" != "${TARGET/e2e/}" ]; then
        cd server &&
        nohup python manage.py ;
        (nohup honcho start & ) ;
        cd ../client &&
        ./node_modules/protractor/bin/protractor protractor-conf.js --stackTrace --verbose ;
      fi

after_script:
    - killall -9 python
    - rm .npm/*.lock


