version: 1
disable_existing_loggers: true
loggers:
 superdesk:
  level: DEBUG
 superdesk.ws:
  level: DEBUG
 superdesk.websockets_comms:
  level: DEBUG
 flask.ext.cors:
  level: DEBUG
 elasticsearch:
  level: DEBUG
 ldap:
  level: DEBUG
 worker:
  level: DEBUG
