mongodb:
  image: mongo:2.6
  volumes:
   - ../data/mongodb:/data/db

redis:
  image: redis:2.8
  volumes:
   - ../data/redis:/data

logstash:
  image: logstash:1.5
  command: logstash -f /usr/share/logstash/logstash.conf
  volumes:
  - ./logstash:/usr/share/logstash

kibana:
  build: kibana
  restart: always

elastic:
  image: elasticsearch:1.5
  volumes:
   - ../data/elastic:/usr/share/elasticsearch/data

postfix:
  image: catatnight/postfix
  environment:
  - maildomain=mail.sourcefabric.org
  - smtp_user=user:pwd

superdesk:
  build: ../
  environment:
   - MONGO_URI=mongodb://mongodb/test
   - PUBLICAPI_MONGO_URI=mongodb://mongodb/test
   - LEGAL_ARCHIVE_URI=mongodb://mongodb/test
   - ELASTICSEARCH_URL=http://elastic:9200
   - ELASTICSEARCH_INDEX
   - CELERY_BROKER_URL=redis://redis:6379/1
   - REDIS_URL=redis://redis:6379/1
   - LOG_SERVER_ADDRESS=logstash
   - LOG_SERVER_PORT=5555
   - AMAZON_ACCESS_KEY_ID
   - AMAZON_CONTAINER_NAME
   - AMAZON_REGION
   - AMAZON_SECRET_ACCESS_KEY
   - S3_THEMES_PREFIX
   - REUTERS_USERNAME
   - REUTERS_PASSWORD
   - MAIL_SERVER=postfix
   - MAIL_PORT=25
   - MAIL_USE_TLS=false
   - MAIL_USE_SSL=false
   - MAIL_USERNAME=user
   - MAIL_PASSWORD=pwd
   - SENTRY_DSN
   - SUPERDESK_URL=http://127.0.0.1/api
   - SUPERDESK_WS_URL=ws://127.0.0.1/ws
   - SUPERDESK_CLIENT_URL=http://127.0.0.1
   - SUPERDESK_TESTING=True
   - EMBED_PROTOCOL=http://
   - LIVEBLOG_DEBUG=True
   - SYNDICATION=True
   - MONGO_DBNAME=liveblog
   - SUBSCRIPTION_LEVEL=network
   - LIVEBLOG_CACHE_TYPE=simple
   - BOTO_CONFIG=/doesnotexist
   - SYNDICATION_VALIDATE_AUTH=0
   - MAIL_SUPPRESS_SEND=False
   - EMBEDLY_KEY
   - OAUTHLIB_INSECURE_TRANSPORT=1
  volumes:
   - ../results/server/unit:/opt/server/results-unit/
   - ../results/server/behave:/opt/server/results-behave/
   - ../results/client/unit:/opt/server/client/unit-test-results
