services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/data

  elasticsearch-1.7.2:
    container_name: elasticsearch
    image: liveblog3/elasticsearch:1.7.2
    ports:
      - 9200:9200
    volumes:
      - ../data/elastic:/usr/share/elasticsearch/data

  mongodb-3.4.23:
    container_name: mongodb
    image: mongo:3.4.23
    ports:
      - 27017:27017
    volumes:
      - ../data/mongodb:/data/db
