name: "Lint"

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./server"
          version: "~= 22.0"

  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.6.x
      - uses: py-actions/flake8@v2
        with:
          path: "--config=./server/setup.cfg server/"